# Generated by Django 6.0.4 on 2026-09-13 15:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='श्रेणीचे नाव')),
            ],
            options={
                'verbose_name': 'श्रेणी',
                'verbose_name_plural': 'श्रेणी',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='उत्पादनाचे नाव')),
                ('description', models.TextField(blank=True, verbose_name='वर्णन')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='किंमत')),
                ('stock', models.PositiveIntegerField(default=0, verbose_name='साठा')),
                ('image', models.ImageField(blank=True, null=True, upload_to='products/', verbose_name='उत्पादनाचा फोटो')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='तयार केले')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.category', verbose_name='श्रेणी')),
            ],
            options={
                'verbose_name': 'उत्पादन',
                'verbose_name_plural': 'उत्पादने',
            },
        ),
    ]
